### ISSUE TITLE
Question: Pruning capabilities and simultaneous runs

### ISSUE THREAD

**Issue by jzazo** [toshihikoyanase/hydra-optuna-sweeper#1]
Hi! I wanted to ask about using the pruning capabilities of Optuna if using hydra and this plugin. The example does not `import optuna`, so I am wondering if a `trial` object can still be used to use pruning capabilities.

Can we specify the number of simultaneous trials to be run, when multiple cores or gpus are available in a machine? Is this automatic depending on free cores and/or gpus? 

Thanks a lot for this promising plugin!

**Comment by jzazo** [comment]
To my first question, I think one option would be to use the storage capabilities of Optuna, and re-load/re-create the study in the script, and retrieve the trial from the recreated study.

This could be achieved easily if hydra passed the `trial_id` when launching the process (for example inside the for loop [line 102](https://github.com/toshihikoyanase/hydra-optuna-sweeper/blob/758099f556678e826f9eee68d73386ebe25cc37c/hydra_plugins/hydra_optuna_sweeper/optuna_sweeper.py#L102)). Would this be something to consider?

To the second question, `n_jobs` should start multiple processes in parallel, but I think with the limitation that a new batch of processes needs all previous processes to finish.

Let me know if I understood this correctly. Thanks.

**Comment by nzw0301** [comment]
Hi @jzazo, the extended version of this sweeper is in the official hydra -- see https://hydra.cc/docs/next/plugins/optuna_sweeper/ and https://github.com/facebookresearch/hydra/tree/master/plugins/hydra_optuna_sweeper.

**Comment by jzazo** [comment]
Thanks, I already realized that. Will close.
